server:
  port: 8081

spring:
  application:
    name: catalog

#customer:
  #ribbon:
    #listOfServers: localhost:8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka  # default address
    